#!/usr/bin/env bash
# Install a self-contained copy of dots. No shell configuration is modified.
set -euo pipefail

init_ui() {
  if [[ -t 1 && -z ${NO_COLOR:-} ]]; then
    OK=$'\033[32m'; WARN=$'\033[33m'; ERR=$'\033[31m'; DIM=$'\033[2m'; RESET=$'\033[0m'
  else
    OK= WARN= ERR= DIM= RESET=
  fi
}

die() { printf '%sdots: error:%s %s\n' "$ERR" "$RESET" "$*" >&2; exit 1; }

show_path() {
  if [[ $1 == "${HOME%/}/"* ]]; then printf '~/%s' "${1#"${HOME%/}/"}"; else printf '%s' "$1"; fi
}

usage() { cat <<'EOF'
Usage: ./install.sh [--bin-dir <path>]

Install dots as a self-contained executable. The default directory is
$HOME/.local/bin. This script never changes PATH or shell startup files.
EOF
}

expand_home() {
  case $1 in
    '~') printf '%s' "$HOME" ;;
    '~/'*) printf '%s/%s' "$HOME" "${1:2}" ;;
    *) printf '%s' "$1" ;;
  esac
}

path_has_dir() {
  local item canonical
  IFS=: read -r -a _path_parts <<< "${PATH:-}"
  if [[ ${_path_parts[@]+_} ]]; then for item in "${_path_parts[@]}"; do
    [[ -n $item ]] || item=.
    [[ -d $item ]] || continue
    canonical=$(cd "$item" && pwd -P)
    [[ $canonical == "$BIN_DIR" ]] && return 0
  done; fi
  return 1
}

init_ui
BIN_DIR=$HOME/.local/bin
while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      usage
      exit 0
      ;;
    --bin-dir)
      [[ $# -ge 2 ]] || die '--bin-dir requires a path'
      BIN_DIR=$2
      shift 2
      ;;
    *) die "unknown option: $1" ;;
  esac
done

BIN_DIR=$(expand_home "$BIN_DIR")
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
SOURCE=$ROOT/bin/dots
LIBRARY=$ROOT/lib/dots.sh

[[ -x $SOURCE && -r $LIBRARY ]] || die "cannot locate the dots executable in $ROOT"

mkdir -p "$BIN_DIR" || die "cannot create $BIN_DIR"

BIN_DIR=$(cd "$BIN_DIR" && pwd -P)
TARGET=$BIN_DIR/dots

if [[ -e $TARGET || -L $TARGET ]]; then
  [[ ! -d $TARGET && ! -L $TARGET && -f $TARGET && -x $TARGET ]] || die "refusing to replace unexpected target type: $TARGET"
  ACTION="Updating"
else
  ACTION="Installing"
fi

TEMP=$(mktemp "$BIN_DIR/.dots.XXXXXX") || die "cannot create temporary file in $BIN_DIR"
cleanup() { rm -f "$TEMP"; }

trap cleanup EXIT HUP INT TERM
{
  printf '%s\n' '#!/usr/bin/env bash' 'set -euo pipefail' '# Self-contained dots installation; generated by install.sh.'
  cat "$LIBRARY"
  printf '\ndots_main "$@"\n'
} > "$TEMP" || die 'cannot write installed executable'

chmod 755 "$TEMP" || die 'cannot mark installed executable as executable'
mv -f "$TEMP" "$TARGET" || die "cannot install $TARGET"
trap - EXIT HUP INT TERM

printf '%s✓%s %s %s\n' "$OK" "$RESET" "$ACTION" "$(show_path "$TARGET")"

if ! path_has_dir; then
  printf '%s!%s %s is not in PATH; add it to run %sdots%s directly.\n' "$WARN" "$RESET" "$(show_path "$BIN_DIR")" "$DIM" "$RESET" >&2
fi
